#!/usr/bin/env bash

cat <<EOF > /opt/lfg/env
export DATABASE_URL="$PROD_DATABASE_URL"
export DJANGO_ACCOUNT_ALLOW_REGISTRATION="$PROD_DJANGO_ACCOUNT_ALLOW_REGISTRATION"
export DJANGO_ADMIN_URL="$PROD_DJANGO_ACCOUNT_ALLOW_REGISTRATION"
export DJANGO_ALLOWED_HOSTS="$PROD_DJANGO_ALLOWED_HOSTS"
export DJANGO_AWS_ACCESS_KEY_ID="$PROD_DJANGO_AWS_ACCESS_KEY"
export DJANGO_AWS_IS_GZIPPED="$PROD_DJANGO_AWS_IS_GZIPPED"
export DJANGO_AWS_SECRET_ACCESS_KEY="$PROD_DJANGO_AWS_SECRET_ACCESS_KEY"
export DJANGO_AWS_STORAGE_BUCKET_NAME="$PROD_DJANGO_AWS_STORAGE_BUCKET_NAME"
export DJANGO_DEFAULT_FROM_EMAIL="$PROD_DJANGO_DEFAULT_FROM_EMAIL"
export DJANGO_SECRET_KEY="$PROD_DJANGO_SECRET_KEY"
export DJANGO_SENTRY_DSN="$PROD_DJANGO_SENTRY_DSN"
export DJANGO_SETTINGS_MODULE="$PROD_DJANGO_SETTINGS_MODULE"
export MAILGUN_API_KEY="$PROD_MAILGUN_API_KEY"
export MAILGUN_DOMAIN="$PROD_MAILGUN_DOMAIN"
export MAILGUN_PUBLIC_KEY="$PROD_MAILGUN_PUBLIC_KEY"
export MAILGUN_SMTP_SERVER="$PROD_MAILGUN_SMTP_SERVER"
export MAILGUN_SMTP_LOGIN="$PROD_MAILGUN_SMTP_LOGIN"
export MAILGUN_SMTP_PASSWORD="$PROD_MAILGUN_SMTP_PASSWORD"
export MAILGUN_SMTP_PORT="$PROD_MAILGUN_SMTP_PORT"
export REDISCLOUD_URL="$PROD_REDISCLOUD_URL"
export SEARCHBOX_SSL_URL="$PROD_SEARCHBOX_SSL_URL"
export SEARCHBOX_URL="$PROD_SEARCHBOX_URL"
EOF

exit 0
