test:
  image: python:3.7
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: looking_for_group
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
    DJANGO_SETTINGS_MODULE: "config.settings.test"
  before_script:
    - python -V
    - pip install pipenv
    - pipenv sync --dev
  script:
  - pipenv run pytest -n 2

production:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=geek-looking-for-group --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - master
