test:
  image: python:3.7
  services:
    - postgres:latest
    - redis:latest
  variables:
    POSTGRES_DB: looking_for_group
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
    DJANGO_SETTINGS_MODULE: "config.settings.test"
    REDISCLOUD_URL: "redis://redis/1"
  before_script:
    - curl -sL https://deb.nodesource.com/setup_11.x | bash -
    - apt-get install -y nodejs
    - python -V
    - pip install pipenv
    - npm install
    - npm prune --production
    - pipenv sync --dev
  script:
  - pipenv run pytest -n 2
