test:
  image: python:3.7
  services:
    - mdillon/postgis:latest
    - redis:latest
  variables:
    POSTGRES_DB: looking_for_group
    DATABASE_URL: "postgresql://postgres:postgres@mdillon__postgis:5432/$POSTGRES_DB"
    DJANGO_SETTINGS_MODULE: "config.settings.test"
    REDISCLOUD_URL: "redis://redis/1"
  before_script:
    - curl -sL https://deb.nodesource.com/setup_11.x | bash -
    - apt-get install -y nodejs
    - python -V
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
    - npm install
    - npm prune --production
    - poetry install
  script:
  - poetry run pytest -n 2
