# Generated by Django 2.1.1 on 2018-09-11 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameposting',
            name='gm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gmed_games', to='gamer_profiles.GamerProfile'),
        ),
    ]
