# Generated by Django 2.1.1 on 2018-09-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
        ('games', '0002_auto_20180911_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameposting',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='schedule.Event'),
        ),
        migrations.AddField(
            model_name='gameposting',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Occurrence'),
        ),
    ]
