# Generated by Django 2.1.1 on 2018-09-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20180921_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameposting',
            name='start_date',
        ),
        migrations.AddField(
            model_name='gameposting',
            name='session_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Your estimate for how long a session will take in hours.', max_digits=4, null=True, verbose_name='Length (hours)'),
        ),
        migrations.AddField(
            model_name='gameposting',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Date and time of first session.', null=True),
        ),
    ]
