# Generated by Django 2.1.1 on 2018-09-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20180921_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameposting',
            name='game_frequency',
            field=models.CharField(choices=[('weekly', 'Every week'), ('biweekly', 'Every other week'), ('monthly', 'Every month'), ('na', 'N/A'), ('custom', 'Custom: See description for details')], db_index=True, default='na', help_text='How often will this be played?', max_length=15),
        ),
    ]
