# Generated by Django 2.1.1 on 2018-09-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
        ('games', '0006_auto_20180922_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('schedule.event',),
        ),
        migrations.AlterField(
            model_name='gameposting',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.GameEvent'),
        ),
        migrations.AlterField(
            model_name='gameposting',
            name='game_frequency',
            field=models.CharField(choices=[('na', 'Not Applicable'), ('Custom', 'Custom'), ('biweekly', 'Biweekly (every other week)'), ('daily', 'Daily (so hardcore)'), ('monthly', 'Monthly'), ('third_week', 'Every third week'), ('weekly', 'Weekly'), ('yearly', 'Annually')], db_index=True, default='na', help_text='How often will this be played?', max_length=15),
        ),
    ]
