# Generated by Django 2.1.1 on 2018-09-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20180923_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameposting',
            old_name='mix_players',
            new_name='min_players',
        ),
    ]
