# Generated by Django 2.1.1 on 2018-09-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
        ('games', '0008_auto_20180923_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEventRelation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('schedule.eventrelation',),
        ),
        migrations.AddField(
            model_name='gameposting',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='What date does this end? (Only used for adventures/campaigns.) You can set this later if you prefer.', null=True),
        ),
        migrations.AlterField(
            model_name='gameposting',
            name='game_frequency',
            field=models.CharField(choices=[('na', 'Not Applicable'), ('Custom', 'Custom'), ('Daily', 'Will occur once a day'), ('Every other week', 'Repeats every other week.'), ('Every third week', 'Repeat every third week'), ('Hourly', 'Will occur once an hour'), ('Minutely', 'Will occur once a minute'), ('Monthly', 'Will occur once a month'), ('Secondly', 'Will occur once a second.'), ('Weekly', 'Will occur once a week.'), ('Yearly', 'Will occur once a year.')], db_index=True, default='na', help_text='How often will this be played?', max_length=15),
        ),
    ]
