# Generated by Django 2.1.1 on 2018-09-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
        ('games', '0009_auto_20180924_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildOccurenceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_event_occurence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_occurence_link', to='schedule.Occurrence')),
                ('master_event_occurence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_occurence_link', to='schedule.Occurrence')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='childoccurencelink',
            unique_together={('master_event_occurence', 'child_event_occurence')},
        ),
        migrations.AlterIndexTogether(
            name='childoccurencelink',
            index_together={('master_event_occurence', 'child_event_occurence')},
        ),
    ]
