# Generated by Django 2.1.1 on 2018-09-25 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0014_auto_20180822_1307'),
        ('games', '0010_auto_20180924_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureLog',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='A good headline for this session.', max_length=250)),
                ('body', models.TextField(blank=True, help_text='What happened during this session? (You can use Markdown for formatting/links.)', null=True)),
                ('body_rendered', models.TextField(blank=True, null=True)),
                ('initial_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamer_profiles.GamerProfile')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_editor_logs', to='gamer_profiles.GamerProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='player',
            old_name='sessions_attended',
            new_name='sessions_expected',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='players_present',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='players_expected',
            field=models.ManyToManyField(help_text='Players who should be in attendance?', to='games.Player'),
        ),
        migrations.AddField(
            model_name='adventurelog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameSession'),
        ),
    ]
