# Generated by Django 2.1.1 on 2018-09-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20180925_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('pending', 'Scheduled'), ('cancel', 'Cancelled'), ('complete', 'Completed')], db_index=True, default='pending', max_length=15),
        ),
    ]
