# Generated by Django 2.1.2 on 2018-10-17 17:07

from django.db import migrations, models


def add_missing_slugs(apps, schema_editor):
    models_to_add = ['AdventureLog', 'Character', 'GamePosting', 'GameSession', 'Player']
    for model_name in models_to_add:
        MyModel = apps.get_model('games', model_name)
        for obj in MyModel.objects.all():
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_gamesession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurelog',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gameposting',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(add_missing_slugs, reverse_code=migrations.RunPython.noop),
    ]
