# Generated by Django 2.1.2 on 2018-10-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20181017_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameposting',
            options={'ordering': ['status', 'start_time', '-end_date', '-created']},
        ),
        migrations.AddField(
            model_name='gameposting',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('started', 'In Progress'), ('replace', 'Seeking replacement player'), ('cancel', 'Cancelled'), ('closed', 'Completed')], db_index=True, default='open', help_text='Current game status', max_length=10),
        ),
        migrations.AlterField(
            model_name='gameposting',
            name='game_frequency',
            field=models.CharField(choices=[('weekly', 'Every week'), ('biweekly', 'Every other week'), ('monthly', 'Every month'), ('na', 'N/A'), ('custom', 'Custom: See description for details')], db_index=True, default='na', help_text='How often will this be played?', max_length=15),
        ),
    ]
