# Generated by Django 2.1.2 on 2018-10-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20181017_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurelog',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gameposting',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
