# Generated by Django 2.1.2 on 2018-10-18 20:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0014_auto_20180822_1307'),
        ('games', '0015_auto_20181018_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePostingApplication',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('message', models.TextField(help_text='Please include a message with your application.')),
                ('status', models.CharField(choices=[('new', 'Awaiting submission.'), ('pending', 'Pending Review'), ('deny', 'Denied'), ('approve', 'Approved')], db_index=True, default='new', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='gameposting',
            name='privacy_level',
            field=models.CharField(choices=[('private', 'Private Link (unlisted)'), ('community', 'Friends/Selected Communities'), ('public', 'Public')], db_index=True, default='private', help_text='Choose the privacy level for this posting.', max_length=15),
        ),
        migrations.AddField(
            model_name='gamepostingapplication',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GamePosting'),
        ),
        migrations.AddField(
            model_name='gamepostingapplication',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamer_profiles.GamerProfile'),
        ),
    ]
