# Generated by Django 2.1.2 on 2018-10-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20181018_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurelog',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.GameSession'),
        ),
        migrations.AlterField(
            model_name='gameposting',
            name='game_frequency',
            field=models.CharField(choices=[('na', 'Not Applicable'), ('Custom', 'Custom'), ('biweekly', 'Biweekly (every other week)'), ('daily', 'Daily (so hardcore)'), ('monthly', 'Monthly'), ('third_week', 'Every third week'), ('weekly', 'Weekly'), ('yearly', 'Annually')], db_index=True, default='na', help_text='How often will this be played?', max_length=15),
        ),
    ]
