# Generated by Django 2.1.2 on 2018-10-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20181020_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameposting',
            name='game_description',
            field=models.TextField(default='Blah', help_text='Description of the game.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameposting',
            name='game_frequency',
            field=models.CharField(choices=[('weekly', 'Every week'), ('biweekly', 'Every other week'), ('monthly', 'Every month'), ('na', 'N/A'), ('custom', 'Custom: See description for details')], db_index=True, default='na', help_text='How often will this be played?', max_length=15),
        ),
    ]
