# Generated by Django 2.1.2 on 2018-10-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_auto_20181025_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(blank=True, help_text='A brief description of this character, e.g. "Half-elf monk"', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='sheet',
            field=models.FileField(blank=True, help_text='Upload your character sheet here.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gameposting',
            name='game_frequency',
            field=models.CharField(choices=[('na', 'Not Applicable'), ('Custom', 'Custom'), ('biweekly', 'Biweekly (every other week)'), ('daily', 'Daily (so hardcore)'), ('monthly', 'Monthly'), ('third_week', 'Every third week'), ('weekly', 'Weekly'), ('yearly', 'Annually')], db_index=True, default='na', help_text='How often will this be played?', max_length=15),
        ),
    ]
