# Generated by Django 2.1.2 on 2018-11-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20181028_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameposting',
            name='communities',
            field=models.ManyToManyField(help_text='Which communities would you like to post this in? (Optional)', to='gamer_profiles.GamerCommunity'),
        ),
        migrations.AlterField(
            model_name='gameposting',
            name='game_frequency',
            field=models.CharField(choices=[('weekly', 'Every week'), ('biweekly', 'Every other week'), ('monthly', 'Every month'), ('na', 'N/A'), ('custom', 'Custom: See description for details')], db_index=True, default='na', help_text='How often will this be played?', max_length=15),
        ),
    ]
