# Generated by Django 2.1.2 on 2018-11-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ('games', '0020_auto_20181102_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameposting',
            name='game_frequency',
            field=models.CharField(choices=[('na', 'Not Applicable'), ('Custom', 'Custom'), ('biweekly', 'Biweekly (every other week)'), ('daily', 'Daily (so hardcore)'), ('monthly', 'Monthly'), ('third_week', 'Every third week'), ('weekly', 'Weekly'), ('yearly', 'Annually')], db_index=True, default='na', help_text='How often will this be played?', max_length=15),
        ),
    ]
