# Generated by Django 2.1.2 on 2018-11-04 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_auto_20181102_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameposting',
            name='published_game',
            field=models.ForeignKey(blank=True, help_text='What type of game are you playing, e.g. D&D5E? Leave blank for homebrew.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_catalog.GameEdition'),
        ),
    ]
