# Generated by Django 2.1.2 on 2018-11-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_auto_20181104_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameposting',
            name='communities',
            field=models.ManyToManyField(blank=True, help_text='Which communities would you like to post this in? (Optional)', to='gamer_profiles.GamerCommunity'),
        ),
    ]
