# Generated by Django 2.1.2 on 2018-11-08 15:52

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0012_auto_20181105_1302'),
        ('taggit', '0002_auto_20150616_2121'),
        ('games', '0024_auto_20181106_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameposting',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='game_catalog.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
