# Generated by Django 2.1.3 on 2018-11-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_gameposting_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameposting',
            options={'ordering': ['status', 'start_time', '-end_date', '-created'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterField(
            model_name='gameposting',
            name='max_players',
            field=models.PositiveIntegerField(default=3, help_text='Max number of players that will be in the game, excluding GM.'),
        ),
        migrations.AlterField(
            model_name='gameposting',
            name='min_players',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of players needed to schedule this game, excluding the GM.'),
        ),
    ]
