# Generated by Django 2.1.3 on 2018-11-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_auto_20181110_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameposting',
            name='end_date',
            field=models.DateField(blank=True, help_text='What date does this end? (Only used for adventures/campaigns.) You can set this later if you prefer.', null=True),
        ),
    ]
