# Generated by Django 2.1.3 on 2018-11-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_auto_20181113_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameposting',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the game to give players a flavor of your game.', null=True, upload_to='', verbose_name='Featured image'),
        ),
        migrations.AddField(
            model_name='gameposting',
            name='featured_image_cw',
            field=models.CharField(blank=True, help_text='Content warning for featured image, if applicable. If populated, we will hide the featured image behind a warning that users must dismiss.', max_length=50, null=True, verbose_name='Featured image content warning'),
        ),
    ]
