# Generated by Django 2.1.3 on 2018-11-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_gamesession_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Cannot be used with occurrence. For ad hoc events only.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.GameEvent'),
        ),
    ]
