# Generated by Django 2.1.3 on 2018-11-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_gamesession_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='event',
        ),
    ]
