# Generated by Django 2.1.4 on 2018-12-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
        ('games', '0031_remove_gamesession_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCalendar',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('schedule.calendar',),
        ),
    ]
