# Generated by Django 2.1.8 on 2019-04-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_availablecalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameposting',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the game to give players a flavor of your game.', null=True, upload_to='games/game_feature_images/%Y/%m/%d', verbose_name='Featured image'),
        ),
    ]
