# Generated by Django 2.1.8 on 2019-05-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_auto_20190424_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameposting',
            name='featured_image_description',
            field=models.CharField(blank=True, help_text='Description of your featured image for the visually impaired.', max_length=255, null=True, verbose_name='Featured image description'),
        ),
    ]
