# Generated by Django 2.2.4 on 2019-08-20 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('games', '0034_gameposting_featured_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameposting',
            name='game_location',
            field=models.ForeignKey(blank=True, help_text='For an IRL game, where will we play?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location', verbose_name='Game Location'),
        ),
        migrations.AddField(
            model_name='gameposting',
            name='game_mode',
            field=models.CharField(choices=[('online', 'Discord/Roll20/Other'), ('irl', 'IRL/Face to Face'), ('post', 'Play by Post')], default='online', max_length=25),
        ),
    ]
