# Generated by Django 2.2.4 on 2019-08-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_auto_20190820_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameposting',
            name='game_mode',
            field=models.CharField(choices=[('online', 'Discord/Roll20/Other'), ('irl', 'IRL/Face to Face'), ('post', 'Play by Post')], db_index=True, default='online', max_length=25),
        ),
    ]
