# Generated by Django 2.0.7 on 2018-07-05 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0001_squashed_0002_gamercommunity_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamerFriendRequest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'Pending'), ('accept', 'Accepted'), ('reject', 'Rejected')], default='new', help_text='Current request status.', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, help_text='Other friends.', to='gamer_profiles.GamerProfile'),
        ),
        migrations.AddField(
            model_name='gamerfriendrequest',
            name='recipient',
            field=models.ForeignKey(help_text="Will they or won't they?", on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to='gamer_profiles.GamerProfile'),
        ),
        migrations.AddField(
            model_name='gamerfriendrequest',
            name='requestor',
            field=models.ForeignKey(help_text='Who asked to friend?', on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to='gamer_profiles.GamerProfile'),
        ),
    ]
