# Generated by Django 2.0.7 on 2018-07-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0003_auto_20180705_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='private',
            field=models.BooleanField(default=False, help_text='Only allow GMs and communities I belong/apply to see profile.'),
        ),
    ]
