# Generated by Django 2.0.7 on 2018-07-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0004_gamerprofile_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerprofile',
            name='private',
            field=models.BooleanField(default=True, help_text='Only allow GMs and communities I belong/apply to see profile.'),
        ),
    ]
