# Generated by Django 2.0.7 on 2018-07-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0005_auto_20180705_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='one_shots',
            field=models.BooleanField(db_index=True, default=False, help_text='Interested in one-shots?'),
        ),
    ]
