# Generated by Django 2.0.7 on 2018-07-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0006_gamerprofile_one_shots'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamercommunity',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
