# Generated by Django 2.0.7 on 2018-07-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0007_gamercommunity_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamercommunity',
            name='member_count',
            field=models.PositiveIntegerField(default=0, help_text='Current total count of members.'),
        ),
    ]
