# Generated by Django 2.0.7 on 2018-07-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0008_auto_20180709_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamercommunity',
            options={'ordering': ['name']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='communitymembership',
            order_with_respect_to='community',
        ),
    ]
