# Generated by Django 2.1 on 2018-08-12 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0009_auto_20180710_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityapplication',
            options={'ordering': ['community__name', 'modified']},
        ),
    ]
