# Generated by Django 2.1.3 on 2018-11-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0014_auto_20180822_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerprofile',
            name='rpg_experience',
            field=models.TextField(blank=True, help_text='A few words about your RPG experience. (Visible to GM.)', null=True, verbose_name='RPG Experience'),
        ),
        migrations.AlterField(
            model_name='gamerprofile',
            name='ttgame_experience',
            field=models.TextField(blank=True, help_text='A few words about your non-RPG tabletop experience. (Visible to GM)', null=True, verbose_name='Tabletop game experience'),
        ),
    ]
