# Generated by Django 2.1.3 on 2018-11-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0016_auto_20181110_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamercommunity',
            name='community_logo_cw',
            field=models.CharField(blank=True, help_text="Content warning for community logo, if applicable. If populated, we'll initially hide the logo behind a warning.", max_length=50, null=True, verbose_name='Logo content warning'),
        ),
        migrations.AddField(
            model_name='gamercommunity',
            name='community_logo_image',
            field=models.ImageField(blank=True, help_text='Optional featured logo for your community.', null=True, upload_to='', verbose_name='Community Logo'),
        ),
    ]
