# Generated by Django 2.1.3 on 2018-11-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0017_auto_20181114_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamercommunity',
            old_name='community_logo_image',
            new_name='community_logo',
        ),
    ]
