# Generated by Django 2.1.8 on 2019-04-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0019_auto_20181222_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamercommunity',
            name='community_logo',
            field=models.ImageField(blank=True, help_text='Optional featured logo for your community.', null=True, upload_to='social/community_logos/%Y/%m/%d', verbose_name='Community Logo'),
        ),
    ]
