# Generated by Django 2.1.8 on 2019-04-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0020_auto_20190424_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='gm_games_finished',
            field=models.PositiveIntegerField(default=0, help_text='How many games has this GM completed?'),
        ),
        migrations.AlterField(
            model_name='gamerprofile',
            name='games_finished',
            field=models.PositiveIntegerField(default=0, help_text='How many finished games has this user participated in as a player?'),
        ),
    ]
