# Generated by Django 2.1.8 on 2019-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0023_auto_20190503_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymembership',
            name='game_notifications',
            field=models.BooleanField(db_index=True, default=False, help_text='Receiving notifications about new games posted in this community?', verbose_name='Game Notifications'),
        ),
    ]
