# Generated by Django 2.1.8 on 2019-05-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0024_communitymembership_game_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamercommunity',
            name='community_logo_description',
            field=models.CharField(blank=True, help_text='Brief description of your logo for the visually impaired.', max_length=255, null=True, verbose_name='Community Logo Description'),
        ),
    ]
