# Generated by Django 2.2.4 on 2019-08-29 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20190828_1618'),
        ('gamer_profiles', '0025_gamercommunity_community_logo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='city',
            field=models.ForeignKey(blank=True, help_text='You can optionally list the city where you are to find similar gamers. If your profile is set to private, only your fellow community members and people you are playing games with can see this information.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location'),
        ),
    ]
