# Generated by Django 2.2.6 on 2019-11-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_profiles', '0026_gamerprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='games_kicked',
            field=models.PositiveIntegerField(default=0, help_text='How many times has this user been kicked out of a game by a GM?'),
        ),
    ]
