# Generated by Django 2.1.4 on 2018-12-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='email_messages',
            field=models.BooleanField(default=False, help_text='When a user sends me a message, send a copy of it to my email.', verbose_name='Email messages'),
        ),
    ]
