# Generated by Django 2.0.6 on 2018-06-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesystem',
            name='ogl_license',
            field=models.BooleanField(default=False, help_text='Released under an Open Gaming License?'),
        ),
    ]
