# Generated by Django 2.0.6 on 2018-06-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0002_auto_20180611_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepublisher',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gamesystem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='publishedgame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='publishedmodule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
