# Generated by Django 2.0.6 on 2018-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0004_auto_20180623_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesystem',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Release/publication date of this system.', null=True),
        ),
        migrations.AddField(
            model_name='publishedgame',
            name='edition',
            field=models.CharField(default='1', help_text='Common edition name for this version of the game.', max_length=25),
        ),
        migrations.AddField(
            model_name='publishedgame',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Release/publication date of game.', null=True),
        ),
        migrations.AddField(
            model_name='publishedmodule',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Release/publication date for this module.', null=True),
        ),
    ]
