# Generated by Django 2.1 on 2018-08-28 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0005_auto_20180623_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamepublisher',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='gamesystem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='publishedgame',
            options={'ordering': ['title', '-publication_date']},
        ),
        migrations.AlterModelOptions(
            name='publishedmodule',
            options={'ordering': ['title', '-publication_date']},
        ),
        migrations.AlterField(
            model_name='publishedgame',
            name='game_system',
            field=models.ForeignKey(blank=True, help_text='Rules system the game is based upon.', null=True, on_delete=django.db.models.deletion.CASCADE, to='game_catalog.GameSystem'),
        ),
    ]
