# Generated by Django 2.1 on 2018-08-30 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0006_auto_20180828_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesystem',
            options={'ordering': ['name', '-publication_date']},
        ),
        migrations.AlterModelOptions(
            name='publishedgame',
            options={'ordering': ['-publication_date__year', 'title', '-publication_date']},
        ),
    ]
