# Generated by Django 2.1.2 on 2018-11-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0008_auto_20181104_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameedition',
            name='game',
            field=models.ForeignKey(help_text='Which game is this an edition of?', on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='game_catalog.PublishedGame'),
        ),
        migrations.AlterField(
            model_name='gameedition',
            name='game_system',
            field=models.ForeignKey(blank=True, help_text='Which game system does this edition use?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_editions', to='game_catalog.GameSystem'),
        ),
        migrations.AlterField(
            model_name='sourcebook',
            name='edition',
            field=models.ForeignKey(help_text='Edition this relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='sourcebooks', to='game_catalog.GameEdition'),
        ),
    ]
