# Generated by Django 2.1.2 on 2018-11-04 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0010_auto_20181104_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedgame',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='publishedgame',
            name='game_system',
        ),
        migrations.RemoveField(
            model_name='publishedgame',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='publishedgame',
            name='publisher',
        ),
    ]
