# Generated by Django 2.1.2 on 2018-11-04 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0010_auto_20181104_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedmodule',
            name='parent_game_edition',
            field=models.ForeignKey(blank=True, help_text='Edition that this module uses for play.', null=True, on_delete=django.db.models.deletion.CASCADE, to='game_catalog.GameEdition'),
        ),
    ]
