# Generated by Django 2.1.2 on 2018-11-05 18:02

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0011_publishedmodule_parent_game_edition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishedgame',
            options={'ordering': ['title', '-publication_date']},
        ),
        migrations.AlterField(
            model_name='gameedition',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='game_catalog.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='gamesystem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='game_catalog.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='publishedgame',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='game_catalog.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='publishedmodule',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='game_catalog.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='sourcebook',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='game_catalog.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
