# Generated by Django 2.1.3 on 2018-11-19 02:29

from django.db import migrations, models
from markdown import markdown


def render_legacy_markdown(apps, schema_editor):
    Game = apps.get_model('game_catalog', 'PublishedGame')
    Edition = apps.get_model('game_catalog', 'GameEdition')
    System = apps.get_model('game_catalog', 'GameSystem')

    for model in [Game, Edition, System]:
        for obj in model.objects.all():
            if obj.description:
                obj.description_rendered = markdown(obj.description)
                obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0012_auto_20181105_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameedition',
            name='description_rendered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesystem',
            name='description_rendered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishedgame',
            name='description_rendered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(render_legacy_markdown, reverse_code=migrations.RunPython.noop),
    ]
