# Generated by Django 2.1.4 on 2018-12-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0013_auto_20181118_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepublisher',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the publisher.', null=True),
        ),
    ]
