# Generated by Django 2.1.8 on 2019-04-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0014_gamepublisher_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameedition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/game_edition_covers/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='gamepublisher',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/publisher_logos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='gamesystem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/game_system_covers/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='publishedgame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/base_game_covers/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='publishedmodule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/module_covers/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sourcebook',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of book cover, if available.', null=True, upload_to='catalog/sourcebook_covers/%Y/%m/%d'),
        ),
    ]
