# Generated by Django 2.1.8 on 2019-04-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0015_auto_20190424_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcebook',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='Publisher of this sourcebook.', null=True, on_delete=django.db.models.deletion.CASCADE, to='game_catalog.GamePublisher'),
        ),
    ]
