# Generated by Django 2.1.8 on 2019-04-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0017_sourcebook_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcebook',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='Publisher of this sourcebook.', on_delete=django.db.models.deletion.CASCADE, to='game_catalog.GamePublisher'),
        ),
    ]
