# Generated by Django 2.1.8 on 2019-05-02 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isbn_field.fields
import isbn_field.validators
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_catalog', '0019_auto_20190426_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedAddition',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=30)),
                ('title', models.CharField(help_text='Name or title of suggested addition.', max_length=255, verbose_name='Name/Title')),
                ('description', models.TextField(blank=True, help_text='Description for the addition.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Cover image or logo', null=True, upload_to='catalog/suggested_additions/%Y/%m/%d')),
                ('url', models.URLField(blank=True, help_text='Suggested url field', null=True)),
                ('ogl_license', models.BooleanField(help_text='Is this released under an OGL license?')),
                ('release_date', models.DateField(blank=True, help_text='Release date for addition. When was this published?', null=True)),
                ('isbn', isbn_field.fields.ISBNField(blank=True, help_text='ISBN for item, if applicable', max_length=28, null=True, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('suggested_tags', models.CharField(blank=True, help_text='Comma seperated list of suggested tags', max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Suggested Addition',
                'ordering': ['-created', 'status'],
            },
        ),
        migrations.CreateModel(
            name='SuggestedCorrection',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=30)),
                ('object_id', models.CharField(db_index=True, max_length=90)),
                ('new_title', models.CharField(blank=True, help_text='Suggested title/name change, if any.', max_length=255, null=True, verbose_name='New Name/Title')),
                ('new_isbn', isbn_field.fields.ISBNField(blank=True, help_text='ISBN of item, if applicable', max_length=28, null=True, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('new_release_date', models.DateField(blank=True, help_text='Suggested change to the release date.', null=True)),
                ('new_url', models.DateField(blank=True, help_text='New suggested url', null=True)),
                ('new_image', models.ImageField(blank=True, null=True, upload_to='catalog/corrections/%Y/%m/%d')),
                ('new_description', models.TextField(blank=True, help_text='New description, if applicable to object.', null=True)),
                ('new_tags', models.CharField(blank=True, help_text='Suggested tags for the item', max_length=255, null=True)),
                ('other_notes', models.TextField(blank=True, help_text='Any other details or suggestions we should incorporate into the correction.', null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_corrections', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggested Correction',
                'ordering': ['-created', 'status'],
            },
        ),
        migrations.AlterModelOptions(
            name='gameedition',
            options={'verbose_name': 'Game Edition'},
        ),
        migrations.AlterModelOptions(
            name='gamepublisher',
            options={'ordering': ['name'], 'verbose_name': 'Publisher'},
        ),
        migrations.AlterModelOptions(
            name='gamesystem',
            options={'ordering': ['name', '-publication_date'], 'verbose_name': 'Game System'},
        ),
        migrations.AlterModelOptions(
            name='publishedgame',
            options={'ordering': ['title', '-publication_date'], 'verbose_name': 'Published Game'},
        ),
        migrations.AlterModelOptions(
            name='publishedmodule',
            options={'ordering': ['title', '-publication_date'], 'verbose_name': 'Module/Adventure'},
        ),
        migrations.AlterModelOptions(
            name='sourcebook',
            options={'verbose_name': 'Source Book'},
        ),
        migrations.AddField(
            model_name='suggestedaddition',
            name='edition',
            field=models.ForeignKey(blank=True, help_text='For which edition?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_catalog.GameEdition'),
        ),
        migrations.AddField(
            model_name='suggestedaddition',
            name='game',
            field=models.ForeignKey(blank=True, help_text='For what game?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_catalog.PublishedGame'),
        ),
        migrations.AddField(
            model_name='suggestedaddition',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='Publisher of item.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_catalog.GamePublisher'),
        ),
        migrations.AddField(
            model_name='suggestedaddition',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_additions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestedaddition',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_additions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestedaddition',
            name='system',
            field=models.ForeignKey(blank=True, help_text='System this edition is based upon?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_catalog.GameSystem'),
        ),
    ]
