# Generated by Django 2.1.8 on 2019-05-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalog', '0020_auto_20190501_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedcorrection',
            name='new_url',
            field=models.URLField(blank=True, help_text='New suggested url', null=True),
        ),
    ]
