# Generated by Django 2.1 on 2018-08-22 20:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamer_profiles', '0014_auto_20180822_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDiscordLink',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord', to='gamer_profiles.GamerCommunity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discord_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('icon_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GamerDiscordLink',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gamer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord', to='gamer_profiles.GamerProfile')),
                ('servers', models.ManyToManyField(to='discord.DiscordServer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='communitydiscordlink',
            name='servers',
            field=models.ManyToManyField(to='discord.DiscordServer'),
        ),
    ]
