# Generated by Django 2.1 on 2018-08-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydiscordlink',
            name='servers',
            field=models.ManyToManyField(related_name='communities', to='discord.DiscordServer'),
        ),
        migrations.AlterField(
            model_name='gamerdiscordlink',
            name='servers',
            field=models.ManyToManyField(related_name='gamers', to='discord.DiscordServer'),
        ),
    ]
