# Generated by Django 2.1 on 2018-08-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('discord', '0002_auto_20180822_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerdiscordlink',
            name='socialaccount',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discord_link', to='socialaccount.SocialAccount'),
            preserve_default=False,
        ),
    ]
