# Generated by Django 2.2.7 on 2019-11-15 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('releasenotes', '0003_releasenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasenote',
            name='release_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2019, 11, 15, 15, 50, 15, 358095, tzinfo=utc), help_text='Official release date for this version.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='releasenotice',
            name='latest_version_shown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='releasenotes.ReleaseNote'),
        ),
    ]
