from django.urls import path

from . import views
from .feeds import GamesICalFeed, UpcomingGamesFeed

app_name = "games"

urlpatterns = [
    path(
        "schedule/api/occurrences/",
        views.CalendarJSONView.as_view(),
        name="api_occurrences",
    ),
    path(
        "schedule/feed/calendar/upcoming/<uuid:gamer>/",
        UpcomingGamesFeed(),
        name="upcoming_events_feed",
    ),
    path("schedule/ical/calendar/<uuid:gamer>/", GamesICalFeed(), name="calendar_ical"),
    path(
        "schedule/calendar/<slug:gamer>/",
        views.CalendarDetail.as_view(),
        name="calendar_detail",
    ),
    path(
        "sessions/<slug:session>/",
        view=views.GameSessionDetail.as_view(),
        name="session_detail",
    ),
    path(
        "sessions/<slug:session>/edit/",
        view=views.GameSessionUpdate.as_view(),
        name="session_edit",
    ),
    path(
        "sessions/<slug:session>/move/",
        view=views.GameSessionMove.as_view(),
        name="session_move",
    ),
    path(
        "sessions/<slug:session>/cancel/",
        view=views.GameSessionCancel.as_view(),
        name="session_cancel",
    ),
    path(
        "sessions/<slug:session>/uncancel/",
        view=views.GameSessionUncancel.as_view(),
        name="session_uncancel",
    ),
    path(
        "sessions/<slug:session>/completetoggle/",
        views.GameSessionCompleteUnComplete.as_view(),
        name="session_complete_toggle",
    ),
    path(
        "my/characters/",
        view=views.CharacterListForGamer.as_view(),
        name="character_gamer_list",
    ),
    path("my/games/", view=views.MyGameList.as_view(), name="my_game_list"),
    path(
        "game/<slug:gameid>/sessions/",
        view=views.GameSessionList.as_view(),
        name="session_list",
    ),
    path(
        "game/<slug:gameid>/export/",
        view=views.ExportGameDataView.as_view(),
        name="game_export",
    ),
    path(
        "game/<slug:slug>/invites/",
        view=views.GameInviteList.as_view(),
        name="game_invite_list",
    ),
    path(
        "game/<slug:gameid>/sessions/create/",
        view=views.GameSessionCreate.as_view(),
        name="session_create",
    ),
    path(
        "game/<slug:gameid>/sessions/create/adhoc/",
        view=views.GameSessionAdHocCreate.as_view(),
        name="session_adhoc_create",
    ),
    path(
        "logs/<slug:log>/edit/",
        view=views.AdventureLogUpdate.as_view(),
        name="log_edit",
    ),
    path(
        "logs/<slug:log>/delete/",
        view=views.AdventureLogDelete.as_view(),
        name="log_delete",
    ),
    path(
        "logs/<slug:session>/create/",
        view=views.AdventureLogCreate.as_view(),
        name="log_create",
    ),
    path(
        "game/<slug:gameid>/", views.GamePostingDetailView.as_view(), name="game_detail"
    ),
    path(
        "game/<slug:gameid>/edit/",
        views.GamePostingUpdateView.as_view(),
        name="game_edit",
    ),
    path(
        "game/<slug:gameid>/delete/",
        views.GamePostingDeleteView.as_view(),
        name="game_delete",
    ),
    path(
        "game/<slug:gameid>/characters/",
        view=views.CharacterListForGame.as_view(),
        name="character_game_list",
    ),
    path(
        "game/<slug:gameid>/apply/",
        views.GamePostingApplyView.as_view(),
        name="game_apply",
    ),
    path(
        "game/<slug:gameid>/applications/",
        view=views.GamePostingApplicantList.as_view(),
        name="game_applicant_list",
    ),
    path(
        "applications/<slug:application>/approval/",
        view=views.GamePostingApplicationApproveReject.as_view(),
        name="game_application_approve_reject",
    ),
    path(
        "applications/<slug:application>/",
        views.GamePostingApplicationDetailView.as_view(),
        name="game_apply_detail",
    ),
    path(
        "applications/<slug:application>/edit/",
        views.GamePostingApplicationUpdateView.as_view(),
        name="game_apply_update",
    ),
    path(
        "applications/<slug:application>/delete/",
        views.GamePostingWithdrawApplication.as_view(),
        name="game_apply_delete",
    ),
    path(
        "applications/",
        views.GamePostingAppliedList.as_view(),
        name="my-game-applications",
    ),
    path(
        "players/<slug:player>/characters/create/",
        views.CharacterCreate.as_view(),
        name="character_create",
    ),
    path(
        "players/<slug:player>/characters/",
        view=views.CharacterListForPlayer.as_view(),
        name="character_player_list",
    ),
    path(
        "characters/<slug:character>/",
        views.CharacterDetail.as_view(),
        name="character_detail",
    ),
    path(
        "characters/<slug:character>/edit/",
        views.CharacterUpdate.as_view(),
        name="character_edit",
    ),
    path(
        "characters/<slug:character>/delete/",
        views.CharacterDelete.as_view(),
        name="character_delete",
    ),
    path(
        "characters/<slug:character>/approve/",
        view=views.CharacterApproveView.as_view(),
        name="character_approve",
    ),
    path(
        "characters/<slug:character>/reject/",
        view=views.CharacterRejectView.as_view(),
        name="character_reject",
    ),
    path(
        "characters/<slug:character>/deactivate/",
        view=views.CharacterMakeInactiveView.as_view(),
        name="character_inactivate",
    ),
    path(
        "characters/<slug:character>/reactivate/",
        view=views.CharacterReactivateView.as_view(),
        name="character_reactivate",
    ),
    path(
        "game/<slug:gameid>/<slug:player>/leave/",
        view=views.PlayerLeaveGameView.as_view(),
        name="player_leave",
    ),
    path(
        "game/<slug:gameid>/<slug:player>/kick/",
        view=views.PlayerKickView.as_view(),
        name="player_kick",
    ),
    path("create/", views.GamePostingCreateView.as_view(), name="game_create"),
    path("sessions/<slug:session>/checkconflicts/", view=views.GameSessionRescheduleCheckConflicts.as_view(), name='check_existing_session_conflict'),
    path("", views.GamePostingListView.as_view(), name="game_list"),
]
