# Generated by Django 2.1.3 on 2018-11-21 19:39

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MOTD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('enabled', models.BooleanField(default=True, help_text='Should this be included in the potential results for a message of the day?')),
                ('timebased', models.BooleanField(default=False, help_text='Is this message based on a date range or should it always be an option?')),
                ('start', models.DateTimeField(blank=True, help_text='The earliest time this message should begin appearing.', null=True)),
                ('end', models.DateTimeField(blank=True, help_text='The latest time this message should appear.', null=True)),
                ('message', models.CharField(help_text='The plain text of the message you want to appear.', max_length=250)),
            ],
            options={
                'verbose_name': 'MOTD',
                'verbose_name_plural': 'MOTDs',
                'ordering': ['-end', '-start'],
            },
        ),
    ]
