# Generated by Django 2.1.3 on 2018-11-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motd',
            name='monospace',
            field=models.BooleanField(default=False, help_text='Display this message using a monospace typeface.'),
        ),
    ]
