# Generated by Django 2.1.3 on 2018-11-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motd', '0002_motd_monospace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motd',
            name='message',
            field=models.TextField(help_text='The plain text of the message you want to appear.', max_length=500),
        ),
    ]
