# Generated by Django 2.1.4 on 2018-12-14 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('spam', 'Spam'), ('harrassment', 'Harassment')], db_index=True, default='spam', help_text='Which type of complaint?', max_length=20)),
                ('details', models.TextField(blank=True, help_text='Any addtional details you can provide to help us while we evaluate this complaint.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'In review'), ('done', 'Completed')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Site administrator response.', null=True)),
                ('message', models.ForeignKey(help_text='The offending message.', on_delete=django.db.models.deletion.CASCADE, related_name='related_complaints', to='postman.Message')),
                ('plaintiff', models.ForeignKey(help_text='Who is this report about?', on_delete=django.db.models.deletion.CASCADE, related_name='complaints_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='Who reported this message.', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SilencedUser',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ending', models.DateTimeField(blank=True, help_text='When does the silencing period end? Leave blank for eternal silence.', null=True)),
                ('related_report', models.ForeignKey(help_text='The report that initiaited this silence.', on_delete=django.db.models.deletion.CASCADE, to='mailnotify.MessageReport')),
                ('user', models.ForeignKey(help_text='User silenced.', on_delete=django.db.models.deletion.CASCADE, related_name='silence_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
