# Generated by Django 2.1.4 on 2018-12-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailnotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereport',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
