# Generated by Django 2.1.8 on 2019-04-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgcollections', '0002_auto_20190421_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='in_pdf',
            field=models.BooleanField(default=False, help_text='Do you have a PDF/Ebook copy of this book?'),
        ),
        migrations.AlterField(
            model_name='book',
            name='in_print',
            field=models.BooleanField(default=False, help_text='Do you have a print copy of this book?'),
        ),
    ]
