# Generated by Django 2.2.4 on 2019-08-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20190820_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='formatted_address',
            field=models.CharField(blank=True, help_text='Only accepted players can see this.', max_length=255, null=True, verbose_name='Address'),
        ),
    ]
